project:
  title: 'Vorlesung "Datenanalyse in der Biologie"'
  type: website
  output-dir: _html

toc: true

toc-depth: 3

execute:
  freeze: auto

website: 
  sidebar:
#    contents: auto
    search: true
